(
 (settings(
  (pomodoro_duration 0.2)
  (short_break_duration 0.1)
  (long_break_duration 0.15)
  (ticking_command "ogg123 ~/clock_ticking.ogv &>/dev/null")
  (ringing_command "ogg123 ~/bell_sound.ogv &>/dev/null")
 ))
 (tasks(
  ;; (((name "Task name") (description "Task description")
  ;;   (done_at ("2016-09-10T15:42:38")) (done_with (5)))
   ((name "Task 1") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2") (description "Some fields are optional"))
   ((name "Task 3") (description "three"))
   ((name "Task 4") (description "four"))
   ((name "Task 5") (description "five"))
   ((name "Task 1bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 22bis") (description "Some fields are optional"))
   ((name "Task 33bis") (description "three"))
   ((name "Task 44bis") (description "four"))
   ((name "Task 55bis") (description "five"))
   ((name "Task 11bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 222bis") (description "Some fields are optional"))
   ((name "Task 333bis") (description "three"))
   ((name "Task 444bis") (description "four"))
   ((name "Task 555bis") (description "five"))
   ((name "Task 111bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2222bis") (description "Some fields are optional"))
   ((name "Task 3333bis") (description "three"))
   ((name "Task 4444bis") (description "four"))
   ((name "Task 5555bis") (description "five"))
   ((name "Task 1111bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 22222bis") (description "Some fields are optional"))
   ((name "Task 33333bis") (description "three"))
   ((name "Task 44444bis") (description "four"))
   ((name "Task 55555bis") (description "five"))
   ((name "Task 11111bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task -3bis") (description "Some fields are optional"))
   ((name "Task -4bis") (description "three"))
   ((name "Task -5bis") (description "four"))
   ((name "Task -6bis") (description "five"))
   ((name "Task -2bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2-3bis") (description "Some fields are optional"))
   ((name "Task 3-4bis") (description "three"))
   ((name "Task 4-5bis") (description "four"))
   ((name "Task 5-6bis") (description "five"))
   ((name "Task 1-2bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task -3-32bis") (description "Some fields are optional"))
   ((name "Task -4-43bis") (description "three"))
   ((name "Task -5-54bis") (description "four"))
   ((name "Task -6-65bis") (description "five"))
   ((name "Task -2-21bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2--33bis") (description "Some fields are optional"))
   ((name "Task 3--44bis") (description "three"))
   ((name "Task 4--55bis") (description "four"))
   ((name "Task 5--66bis") (description "five"))
   ((name "Task 1--22bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task r2bis") (description "Some fields are optional"))
   ((name "Task r3bis") (description "three"))
   ((name "Task r4bis") (description "four"))
   ((name "Task r5bis") (description "five"))
   ((name "Task r1bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task r22bis") (description "Some fields are optional"))
   ((name "Task r33bis") (description "three"))
   ((name "Task r44bis") (description "four"))
   ((name "Task r55bis") (description "five"))
   ((name "Task r11bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2r2bis") (description "Some fields are optional"))
   ((name "Task 3r3bis") (description "three"))
   ((name "Task 4r4bis") (description "four"))
   ((name "Task 5r5bis") (description "five"))
   ((name "Task 1r1bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2r2r2bis") (description "Some fields are optional"))
   ((name "Task 3r3r3bis") (description "three"))
   ((name "Task 4r4r4bis") (description "four"))
   ((name "Task 5r5r5bis") (description "five"))
 ))
)

