(
 (settings(
  (pomodoro_duration 0.2)
  (short_break_duration 0.1)
  (long_break_duration 0.15)
  (ticking_command "ogg123 ~/clock_ticking.ogv &>/dev/null")
  (ringing_command "ogg123 ~/bell_sound.ogv &>/dev/null")
 ))
 (tasks(
  ;; (((name "Task name") (description "Task description")
  ;;   (done_at ("2016-09-10T15:42:38")) (done_with (5)))
   ((name "Task 1") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2") (description "Some fields are optional"))
   ((name "Task 3") (description "three"))
   ((name "Task 4") (description "four"))
   ((name "Task 5") (description "five"))
   ((name "Task 6") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 7") (description "Some fields are optional"))
   ((name "Task 8") (description "three"))
   ((name "Task 9") (description "four"))
   ((name "Task 10") (description "five"))
   ((name "Task 11") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 12") (description "Some fields are optional"))
   ((name "Task 13") (description "three"))
   ((name "Task 14") (description "four"))
   ((name "Task 15") (description "five"))
   ((name "Task 16") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 17") (description "Some fields are optional"))
   ((name "Task 18") (description "three"))
   ((name "Task 19") (description "four"))
   ((name "Task 20") (description "five"))
   ((name "Task 21 ") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 23 ") (description "Some fields are optional"))
   ((name "Task 25 ") (description "three"))
   ((name "Task 27 ") (description "four"))
   ((name "Task 29 ") (description "five"))
   ((name "Task 31 ") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 33 ") (description "Some fields are optional"))
   ((name "Task 35 ") (description "three"))
   ((name "Task 37 ") (description "four"))
   ((name "Task 39 ") (description "five"))
   ((name "Task 41 ") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 43 ") (description "Some fields are optional"))
   ((name "Task 45 ") (description "three"))
   ((name "Task 47 ") (description "four"))
   ((name "Task 49 ") (description "five"))
   ((name "Task 51 ") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 53 ") (description "Some fields are optional"))
   ((name "Task 55 ") (description "three"))
   ((name "Task 57 ") (description "four"))
   ((name "Task 59 ") (description "five"))
   ((name "Task 61 ") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 63 ") (description "Some fields are optional"))
   ((name "Task 65 ") (description "three"))
   ((name "Task 67 ") (description "four"))
   ((name "Task 69 ") (description "five"))
   ((name "Task 71 ") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 73 ") (description "Some fields are optional"))
   ((name "Task 75 ") (description "three"))
   ((name "Task 77 ") (description "four"))
   ((name "Task 79 ") (description "five"))
   ((name "Task 81 ") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 83 ") (description "Some fields are optional"))
   ((name "Task 85 ") (description "three"))
   ((name "Task 87 ") (description "four"))
   ((name "Task 89 ") (description "five"))
   ((name "Task 91 ") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 93 ") (description "Some fields are optional"))
   ((name "Task 95 ") (description "three"))
   ((name "Task 97 ") (description "four"))
   ((name "Task 99 ") (description "five"))
   ((name "Task 101 ") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 103 ") (description "Some fields are optional"))
   ((name "Task 105 ") (description "three"))
   ((name "Task 107 ") (description "four"))
   ((name "Task 109 ") (description "Last"))
 ))
)

