(
 (settings(
  (pomodoro_duration 0.25)
  (short_break_duration 0.15)
  (long_break_duration 0.5)
  (ticking_command "ogg123 ~/clock_ticking.ogv &>/dev/null")
  (ringing_command "ogg123 ~/bell_sound.ogv &>/dev/null")
 ))
 (tasks(
  ;; (((name "Task name") (description "Task description")
  ;;   (done_at ("2016-09-10T15:42:38")) (done_with (5)))
   ((name "Task 1") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2") (description "Some fields are optional"))
   ((name "Task 3") (description "three"))
   ((name "Task 4") (description "four"))
   ((name "Task 5") (description "five"))
   ((name "Task 1bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2bis") (description "Some fields are optional"))
   ((name "Task 3bis") (description "three"))
   ((name "Task 4bis") (description "four"))
   ((name "Task 5bis") (description "five"))
   ((name "Task 1bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2bis") (description "Some fields are optional"))
   ((name "Task 3bis") (description "three"))
   ((name "Task 4bis") (description "four"))
   ((name "Task 5bis") (description "five"))
   ((name "Task 1bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2bis") (description "Some fields are optional"))
   ((name "Task 3bis") (description "three"))
   ((name "Task 4bis") (description "four"))
   ((name "Task 5bis") (description "five"))
   ((name "Task 1bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2bis") (description "Some fields are optional"))
   ((name "Task 3bis") (description "three"))
   ((name "Task 4bis") (description "four"))
   ((name "Task 5bis") (description "five"))
   ((name "Task 1bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2bis") (description "Some fields are optional"))
   ((name "Task 3bis") (description "three"))
   ((name "Task 4bis") (description "four"))
   ((name "Task 5bis") (description "five"))
   ((name "Task 1bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2bis") (description "Some fields are optional"))
   ((name "Task 3bis") (description "three"))
   ((name "Task 4bis") (description "four"))
   ((name "Task 5bis") (description "five"))
   ((name "Task 1bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2bis") (description "Some fields are optional"))
   ((name "Task 3bis") (description "three"))
   ((name "Task 4bis") (description "four"))
   ((name "Task 5bis") (description "five"))
   ((name "Task 1bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2bis") (description "Some fields are optional"))
   ((name "Task 3bis") (description "three"))
   ((name "Task 4bis") (description "four"))
   ((name "Task 5bis") (description "five"))
   ((name "Task 1bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2bis") (description "Some fields are optional"))
   ((name "Task 3bis") (description "three"))
   ((name "Task 4bis") (description "four"))
   ((name "Task 5bis") (description "five"))
   ((name "Task 1bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2bis") (description "Some fields are optional"))
   ((name "Task 3bis") (description "three"))
   ((name "Task 4bis") (description "four"))
   ((name "Task 5bis") (description "five"))
   ((name "Task 1bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2bis") (description "Some fields are optional"))
   ((name "Task 3bis") (description "three"))
   ((name "Task 4bis") (description "four"))
   ((name "Task 5bis") (description "five"))
   ((name "Task 1bis") (description "Learn it!") (done_at "2016-09-10T16:06:41") (done_with 5))
   ((name "Task 2bis") (description "Some fields are optional"))
   ((name "Task 3bis") (description "three"))
   ((name "Task 4bis") (description "four"))
   ((name "Task 5bis") (description "five"))
 ))
)

